Feature Insert Products
2e12/426-scrum-project pull request #54
Opened 2021-01-10 14:59 UTC by LBruegger

Image upload is not finished yet. Needs to be part of the next Story.

2021-01-10 17:25 UTC, 2e12 requested changes

2021-01-10 17:25 UTC, 2e12 commented on frontend/src/app/components/products/insert-product/insert-product.component.html
> +                                        <ion-label position="floating">Preis
Villeicht sollten wir die Währung noch angeben 🤔 (CHF)

2021-01-10 17:25 UTC, 2e12 commented on frontend/src/app/service/product.service.ts
> +    return this.http.post<Product>(this.ROOT_URL + 'products/new', {
The name of the endpoint was changed. Use simply `this.ROOT_URL + 'products'` to avoid a `Method Not Allowed` error 😉

2021-01-10 17:25 UTC, 2e12 commented on frontend/src/app/components/products/insert-product/insert-product.component.ts
> +    formData.append('somekey', 'some value'); // Add any other data you want to send
What does this? 😅

2021-01-10 17:25 UTC, 2e12 commented on frontend/src/app/components/products/insert-product/insert-product.component.ts
> +    // POST formData to Server
I think you can cut this comment (I guess) ✂️

2021-01-10 17:25 UTC, 2e12 commented on frontend/src/app/components/products/insert-product/insert-product.component.ts
> +  ngOnInit() {
What does this?

2021-01-10 17:25 UTC, 2e12 commented on frontend/src/app/components/products/insert-product/insert-product.component.ts
> +  categories = ['Auto', 'Kleidung', 'Mobiliar', 'Sammlerstücke', 'Nicht Zuweisbar'];
Should we also enable custom categories? The backend is able to handle custom values...

2021-01-10 17:29 UTC, 2e12 commented
I would suggest you to merge all the commits to one. Also the commit messages doesn't make much sense to me 🤔 But apart from this good job 👍 I have tested the changes locally and I really like the look you are heading for 😉

2021-01-12 07:15 UTC, LBruegger commented on frontend/src/app/components/products/insert-product/insert-product.component.html
> +                                        <ion-label position="floating">Preis
Sure.

2021-01-12 07:15 UTC, LBruegger commented on frontend/src/app/service/product.service.ts
> +    return this.http.post<Product>(this.ROOT_URL + 'products/new', {
Ok. Changed that.

2021-01-12 07:26 UTC, LBruegger commented on frontend/src/app/components/products/insert-product/insert-product.component.ts
> +  categories = ['Auto', 'Kleidung', 'Mobiliar', 'Sammlerstücke', 'Nicht Zuweisbar'];
Coming in further Story

2021-01-12 07:26 UTC, LBruegger commented on frontend/src/app/components/products/insert-product/insert-product.component.ts
> +    // POST formData to Server
Used for Image Upload

2021-01-12 07:30 UTC, 2e12 approved these changes

2021-01-12 07:30 UTC, merged