Add Categories endpoint
2e12/426-scrum-project pull request #57
Opened 2021-01-12 09:22 UTC by 2e12

2021-01-12 09:24 UTC, LBruegger requested changes
Overall it looks fine

2021-01-12 09:24 UTC, LBruegger commented on backend/products/category.py
> +    return db.query(Category).order_by(Category.name.asc()).offset(skip).limit(limit).all()
instead of limit(limit), I would suggest that you rename it to range

2021-01-12 09:24 UTC, LBruegger commented on backend/products/routes.py
> +    return get_categories(db, skip, limit)
Same here

2021-01-12 09:54 UTC, 2e12 commented
@LBruegger To keep it consistent, I would leave it as it is. The naming scheme has been used in other places as well.
Also the FastAPI documentation suggest this naming https://fastapi.tiangolo.com/tutorial/query-params/

2021-01-13 07:31 UTC, LBruegger commented
> @LBruegger To keep it consistent, I would leave it as it is. The naming scheme has been used in other places as well.
> 
> Also the FastAPI documentation suggest this naming https://fastapi.tiangolo.com/tutorial/query-params/

I see. But Don't you agree that .limit(limit) is cumbersome?

2021-01-13 18:21 UTC, 2e12 commented
@LBruegger I have no problems with it. When we would agree to change, we have to refactor it in the complete project. Which would introduce breaking changes to the API. I'd prefer to stick to the convention.

2021-01-13 19:55 UTC, LBruegger commented
> @LBruegger I have no problems with it. When we would agree to change, we have to refactor it in the complete project. Which would introduce breaking changes to the API. I'd prefer to stick to the convention.

No problem. Therefore leave it as it is, it's fine for me.

2021-01-13 20:41 UTC, merged